import os, sys
sys.path.append(os.path.abspath(".."))

from words_to_number import *
from all_wordifications import all_wordifications
from Utils.utils import keypad

# First layer of testing involves converting a wordified number back to its number equivalent
# and check if the conversion matches the original number

original_number = "1-800-724-6837"
wordified_nums = all_wordifications(original_number)

for word in wordified_nums:
	generated_num = words_to_number(word, original_number)
	assert generated_num == original_number

print("Passing all test cases for converting the wordified number to its original number")

# Second layer of testing involves counting the total number of combinations printed out by
# all_wordifications is correct

num_to_letter, _ = keypad()
valid_number = convert_to_format(original_number, 'xxxxxxxxxx')

total_count = 1
for num in valid_number:
	if num not in "01":
		total_count = total_count*(len(num_to_letter[num])+1)

assert total_count == len(wordified_nums)

print("Passing all test cases for the total number of combinations generated by all_wordifications")


